export const FETCHING_PHOTOS = "FETCHING_PHOTOS";
export const PHOTOS_FETCHED = "PHOTOS_FETCHED";
export const PHOTOS_FETCH_ERROR = "PHOTOS_FETCH_ERROR";

export const SET_SELECTED_PHOTO = "SET_SELECTED_PHOTO";

export const IS_LOADING = "IS_LOADING";
export const LOADED = "LOADED";

export const FETCHING_USER = "FETCHING_USER";
export const RESET_USER = "RESET_USER";
export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_FETCH_FAILED = "USER_FETCH_FAILED";

export const MODAL_OPEN = "MODAL_OPEN";
export const MODAL_CLOSED = "MODAL_CLOSED";
